create table if not exists users
(
    id    bigint generated by default as identity (maxvalue 2147483647)
        constraint pk_user
            primary key,
    name  varchar(255) not null,
    email varchar(512) not null
        constraint uq_user_email
            unique
);

alter table users
    owner to postgres;

create table if not exists items
(
    id           bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    name         varchar(255) not null,
    description  varchar(500) not null,
    is_available boolean default false,
    owner_id     bigint,
    request_id   bigint
);

alter table items
    owner to postgres;


create table if not exists bookings
(
    id         bigint generated by default as identity
        primary key,
    start_date timestamp,
    end_date   timestamp,
    item_id    bigint,
    booker_id  bigint,
    status     booking_status
);

alter table bookings
    owner to postgres;

create table if not exists requests
(
    id           bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    description  varchar(500),
    requestor_id bigint
        constraint requests_users_id_fk
            references users
);

alter table requests
    owner to postgres;

create table if not exists comments
(
    id        bigint generated by default as identity
        primary key,
    text      varchar(500),
    item_id   bigint,
    author_id bigint
);

alter table comments
    owner to postgres;