create table if not exists users
(
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    email varchar(512) not null,
    constraint pk_user primary key (id),
    constraint uq_user_email unique (email)
);

create table if not exists requests
(
    id  bigint generated by default as identity primary key,
    description  varchar(500),
    requestor_id bigint
        constraint requests_users_id_fk
            references users
);

create table if not exists items
(
    id  bigint generated by default as identity primary key,
    name varchar(255) not null,
    description  varchar(500) not null,
    is_available boolean default false,
    owner_id     bigint,
    request_id   bigint
    constraint items_requests_id_fk
    references requests
);

create table if not exists bookings
(
    id  bigint generated by default as identity primary key,
    start_date timestamp without time zone default now(),
    end_date   timestamp without time zone default now(),
    item_id    bigint,
    booker_id  bigint,
    status     varchar
);

create table if not exists comments
(
    id  bigint generated by default as identity primary key,
    text      varchar(500),
    item_id   bigint,
    AUTHOR_ID BIGINT,
    constraint comments_items_id_fk
        foreign key (item_id) references items
);

