create table if not exists users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY(id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE(email)
);

create table if not exists items
(
    id           bigint generated by default as identity
        primary key,
    name         varchar(255) not null,
    description  varchar(500) not null,
    is_available boolean default false,
    owner_id     bigint,
    request_id   bigint
);


create table if not exists bookings
(
    id         bigint generated by default as identity
        primary key,
    start_date timestamp,
    end_date   timestamp,
    item_id    bigint,
    booker_id  bigint,
    status     varchar
);


create table if not exists requests
(
    id           bigint generated by default as identity
        primary key,
    description  varchar(500),
    requestor_id bigint
        constraint requests_users_id_fk
            references users
);



create table if not exists comments
(
    id        bigint generated by default as identity
        primary key,
    text      varchar(500),
    item_id   bigint,
    AUTHOR_ID BIGINT,
    constraint COMMENTS_ITEMS_ID_FK
        foreign key (ITEM_ID) references ITEMS
);

